version: "3.8"
services:
  neoflow-web:
    image: neoflow-web:latest  # Substitua pela sua imagem ou registry
    networks:
      - network_swarm_public
    deploy:
      replicas: 1
      placement:
        constraints:
          # Você pode rodar o Editor no Manager mesmo pois usa poucos recursos
          - node.role == manager
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      labels:
        # Traefik configuration
        - "traefik.enable=true"
        - "traefik.docker.network=network_swarm_public"
        # HTTP redirect to HTTPS
        - "traefik.http.routers.neoflow-web-http.rule=Host(`www.neoflow.com.br`)"
        - "traefik.http.routers.neoflow-web-http.entrypoints=web"
        - "traefik.http.routers.neoflow-web-http.middlewares=redirect-to-https"
        # HTTPS configuration
        - "traefik.http.routers.neoflow-web-https.rule=Host(`www.neoflow.com.br`)"
        - "traefik.http.routers.neoflow-web-https.entrypoints=websecure"
        - "traefik.http.routers.neoflow-web-https.tls=true"
        - "traefik.http.routers.neoflow-web-https.tls.certresolver=myresolver"
        # Service configuration
        - "traefik.http.services.neoflow-web.loadbalancer.server.port=80"
        # Redirect middleware
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"

networks:
  network_swarm_public:
    external: true